### ISSUE TITLE
Resizing App Window Behavior [feedback]

### ISSUE THREAD

**Issue by OsaXma** [flutter/slideplayer#3]
Just as a feedback, I noticed this behavior in the attached gif while resizing the app window. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46427323/53295023-93d0fa80-37b7-11e9-83a3-fb498f0475e3.gif)

**Comment by eseidelGoogle** [comment]
Likely just a bug in FDE.  @stuartmorgan would know.

**Comment by stuartmorgan** [comment]
I haven't seen this specific visual manifestation, but that would be https://github.com/google/flutter-desktop-embedding/issues/171 (which is in turn blocked on a Flutter engine change that makes it possible to avoid having Flutter drawing to the context on another thread during resize).

**Comment by KevinTheGray** [comment]
going to close this as it is an FDE issue and not particular to this project
