### ISSUE TITLE
Slideplayer working with Flutter stable v1.2.1

### ISSUE THREAD

**Issue by asadullah-yousuf-10p** [flutter/slideplayer#4]
I can confirm that it's perfectly working with Flutter stable version 1.2.1. Following is the `flutter doctor` output:
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.31.1)
```

I think *Requirements* section in `README.md` can be updated to reflect the same.

**Comment by KevinTheGray** [comment]
I updated the requirements section with this PR: https://github.com/flutter/slideplayer/pull/7

I marked the version of flutter needed for the most recent version, and the last FDE checkout available for use with the stable branch
