### ISSUE TITLE
Removing the debug tag

### ISSUE THREAD

**Issue by asadullah-yousuf-10p** [flutter/slideplayer#5]
It's fairly trivial to remove the debug banner from the app. Just update `_MyApp.build` method and set `debugShowCheckedModeBanner` property to `false`. The updated build method would look like this:

```
Widget build(BuildContext context) {
    return ScopedModel<FlutterSlidesModel>(
      model: loadedSlides,
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          fontFamily: 'GoogleSans',
        ),
        home: SlidePresentation(),
      ),
    );
  }
```

**Comment by stuartmorgan** [comment]
If you build the app in release mode, checked mode will be disabled:
https://github.com/flutter/slideplayer/blob/master/macos/FlutterWindow.swift#L39

Why would you want to remove the banner unconditionally, even when checked mode is in fact on?

**Comment by asadullah-yousuf-10p** [comment]
@stuartmorgan it's not going away even if I run it in release mode. Any tip?

**Comment by stuartmorgan** [comment]
Ah, i missed the fact that the flag hadn't been updated in this application; it should be `--disable-dart-asserts`.

**Comment by aubykhan** [comment]
I will create a PR for that @stuartmorgan

**Comment by stuartmorgan** [comment]
Line 37, and the comment associated with it, is also out of date; the executable shouldn't be passed as an argument, and IIRC passing a bad argument will cause later arguments not to be processed by the Flutter engine. It looks like the code here was not updated correctly to account for [this FDE change](https://github.com/google/flutter-desktop-embedding/commit/3089a8b0aed02083467ab6c381fa01d3a01cdc81).

**Comment by KevinTheGray** [comment]
this should be fixed with this PR: https://github.com/flutter/slideplayer/pull/6

building in debug/releae will show/not show the debug label
